spring.application.name=role_hierarchy_test
# JPA
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=create
# VALKEY
spring.data.redis.host=localhost
spring.data.redis.port=6389
spring.data.redis.username=sos
spring.data.redis.password=sossos
# Database
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver